language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

# (causes pushes to be ignored?) branches:
     only:
         # Only needed if you are already using branches.only.
         - auto

notifications:
    webhooks: https://homu-ci.herokuapp.com/travis
